// Generate dist/sw.js after the build: a service worker that precaches the
// app shell, the hashed assets, the Stockfish engine and every atlas page,
// so the whole site works offline after one visit.
//
// Strategy: cache-first for static files (all hashed or immutable),
// stale-while-revalidate for page navigations (so deploys propagate on the
// next visit), network-only for everything cross-origin except the Google
// Fonts hosts (cached on first use). No skipWaiting — a new version
// activates when the last old tab closes, so a live session never sees a
// mixed deploy.
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');

if (!existsSync(dist)) {
  console.error('dist/ not found — run the vite build first');
  process.exit(1);
}

// Everything the app needs to boot and play offline.
const PRECACHE_MATCH = [
  /^index\.html$/,
  /^manifest\.webmanifest$/,
  /^favicon\.svg$/,
  /^icons\.svg$/,
  /^icon-\d+\.png$/,
  /^assets\//, // hashed js/css (incl. the openings chunk)
  /^engine\//, // stockfish js + wasm
  /^about\/index\.html$/,
  /^atlas\/.*index\.html$/,
];

const files = [];
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full);
    else files.push(relative(dist, full).replaceAll('\\', '/'));
  }
};
walk(dist);

const precache = files.filter((f) => PRECACHE_MATCH.some((re) => re.test(f))).sort();

// Cache version = content hash of everything precached, so any changed
// byte produces a new cache and activate() drops the old one.
const hash = createHash('sha1');
for (const f of precache) hash.update(f).update(readFileSync(join(dist, f)));
const version = hash.digest('hex').slice(0, 12);

const urls = precache.map((f) => '/' + f);
const totalBytes = precache.reduce((s, f) => s + statSync(join(dist, f)).size, 0);

const sw = `// generated by scripts/build-sw.mjs — do not edit
const CACHE = 'chessography-${version}';
const PRECACHE = ${JSON.stringify(urls)};

// '/about/' -> '/about/index.html', '/' -> '/index.html'
const pageKey = (pathname) => {
  if (pathname.endsWith('/')) return pathname + 'index.html';
  return pathname;
};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k.startsWith('chessography-') && k !== CACHE).map((k) => caches.delete(k)));
      // Control the very first page too, so offline works after a single
      // visit. Safe without skipWaiting: on updates the new worker waits,
      // so claim() never hijacks a live session mid-deploy.
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  const isFont = url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com';
  // Cross-origin (analytics, lichess/chess.com APIs) goes straight to the
  // network — except fonts, which are cached on first use.
  if (url.origin !== location.origin && !isFont) return;

  if (request.mode === 'navigate') {
    // Stale-while-revalidate: pages open instantly from cache, the network
    // refreshes the copy for next time. SPA fallback to the shell.
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        const key = pageKey(url.pathname);
        const cached = await cache.match(key, { ignoreVary: true });
        const refresh = fetch(request)
          .then((res) => {
            if (res.ok) cache.put(key, res.clone());
            return res;
          })
          .catch(() => null);
        if (cached) {
          event.waitUntil(refresh);
          return cached;
        }
        const fresh = await refresh;
        return fresh ?? (await cache.match('/index.html', { ignoreVary: true })) ?? Response.error();
      })(),
    );
    return;
  }

  // Static files: cache-first; anything new (fonts, images) fills the
  // cache on first fetch.
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(request, { ignoreVary: true });
      if (cached) return cached;
      const res = await fetch(request);
      if (res.ok) cache.put(request, res.clone());
      return res;
    })(),
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(
  `sw.js: ${precache.length} precached files (${(totalBytes / 1024 / 1024).toFixed(1)} MB), cache chessography-${version}`,
);
